name: 'setup-r-tensorflow'
description: 'Action to setup r-tensorflow'
author: 'Tomasz Kalinowski'
inputs:
  tf-version:
    description: 'Tensorflow version, passed on to tensorflow::install_tensorflow(version = )'
    default: "default-cpu"
  r-version:
    description: "R version"
    default: "release"
  install-r:
    default: true

runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v2

    - uses: r-lib/actions/setup-r@v2
      id: setup-r
      with:
        r-version: ${{ inputs.r-version }}
        Ncpus: '2L'
        crayon.enabled: 'TRUE'
        use-public-rspm: true
        install-r: ${{ inputs.install-r }}

    - uses: r-lib/actions/setup-r-dependencies@master
      with:
        cache-version: 1 # bump to invalidate cache
        extra-packages: rcmdcheck remotes rstudio/tensorflow

    - name: Install Miniconda
      run: reticulate::install_miniconda()
      shell: Rscript {0}

    - name: Install TensorFlow
      run: tensorflow::install_tensorflow(version = '${{ inputs.tf-version }}')
      shell: Rscript {0}