name: Close 'awaiting reply' issues

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
  - cron: '28 11 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

        stale-issue-label: "awaiting reply"
        stale-pr-label: "awaiting reply"
        days-before-stale: -1

        days-before-close: 30
        close-issue-message: >
          Closing because the issue author has not replied for 30 days.
          Please let us know if you'd like to work on this further and we'll reopen the issue.

