on:
  push:
    branches:
      - master
      - main
  pull_request:
  schedule:
    - cron: '0 1 * * *'

name: R-CMD-check


jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04', 'windows-latest', 'macOS-latest']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@v1
        id: setup-r
        with:
          install-r: true

      - run: echo ${{ steps.setup-r.outputs.installed-r-version }}

      - run: print("hello")
        shell: Rscript {0}


      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=year-week::$(/bin/date -u "+%Y-%U")"
        shell: bash

      - name: Get Info
        shell: bash
        run: |
          env
          ls -al $CONDA
          echo "HOME is $HOME"
          echo "Path is:"
          echo -e ${PATH//:/\\n}

          $CONDA/bin/conda info
          which -a pip
          which -a python
          which -a Rscript
          which -a conda
          conda info
