on:
  push:
    branches:
      - master
      - main
  pull_request:
  schedule:
    - cron: '0 1 * * *'

name: R-CMD-check


jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04', 'windows-latest', 'macOS-latest']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@v1
        id: setup-r
        with:
          install-r: false
          crayon.enabled: 'TRUE'

      - run: |
          # options()
          installed.packages()[,c("LibPath", "Version", "OS_type", "Built")]
          Sys.getenv()
          getwd()
          .libPaths()
          sessionInfo()
          install.packages("sessioninfo")
          sessioninfo::session_info()
          list.files("~")
          # writeLines(readLines(Sys.getenv(~/)))
        shell: Rscript --verbose {0}

      - run: echo ${{ steps.setup-r.outputs.installed-r-version }}

      - run: print("hello")
        shell: Rscript {0}


      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=year-week::$(/bin/date -u "+%Y-%U")"
        shell: bash

      - name: Get Info
        shell: bash
        run: |
          set -x
          export PS4='+(${LINENO}): '
          # export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
          echo $PWD

          env
          ls -al $CONDA
          echo "HOME is $HOME"
          echo "Path is:"
          echo -e ${PATH//:/\\n}


          which -a pip
          which -a python
          which -a Rscript
          which -a conda

          conda info || "executable not found"

          ls $CONDA
          tree $CONDA
          $CONDA/bin/conda info  || "executable not found"
