name: Remove needs-reply label

on:
  workflow_dispatch:
  issue_comment:
    types: [created]
  issues:
    types: [edited]

jobs:
  remove-needs-reply-label:
    runs-on: ubuntu-latest
    steps:
      - name: Remove needs-reply label
        uses: octokit/request-action@v2.x
        continue-on-error: true
        with:
          route: DELETE /repos/:repository/issues/:issue/labels/:label
          repository: ${{ github.repository }}
          issue: ${{ github.event.issue.number }}
          label: needs-reply
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Maybe reopen if closed
        if: success()
        run: >
          curl 
          --request PATCH
          --header "Accept: application/vnd.github.v3+json" 
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' 
          --header 'content-type: application/json' 
          --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
          --data '{"state":"open"}'