name: Close/Lock issues after inactivity

on:
  schedule:
    - cron: "0 0 * * *"

# if upstream action ever breaks, you can just copy the relevant bits into a github-script, e.g.:
# actions/github-script
# https://github.com/facebookresearch/detectron2/blob/master/.github/workflows/needs-reply.yml


jobs:
  close-issues-needs-more-info:
    runs-on: ubuntu-latest
    steps:
      - name: Close issues after no reply
        uses: imhoffd/needs-reply@v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

         
  # lock-issues-after-closed:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.repository_owner == 'facebookresearch' }}
  #   steps:
  #     - name: Lock closed issues that have no activity for a while
  #       uses: dessant/lock-threads@v2
  #       with:
  #         github-token: ${{ github.token }}
  #         issue-lock-inactive-days: '300'
  #         process-only: 'issues'
  #         issue-exclude-labels: 'enhancement,bug,documentation'