name: Remove needs-reply label

on:
  workflow_dispatch:
  issue_comment:
    types: [created]
  issues:
    types: [edited]


jobs:
  reopen-labeled-needs-reply:
    runs-on: ubuntu-latest
    steps:
      - name: Remove needs-reply label and maybe reopen
        # if: contains(github.event.issue.labels.*.name, 'needs-reply')
        run: |
          echo ${{ github.actor }}
          echo ${{ github.event.issue_comment.sender }}
          echo ${{ toJSON(github.event.issue.labels.*.name) }}
          gh issue edit $ISSUE --remove-label "needs-reply"
          gh issue reopen $ISSUE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
