name: Close 'needs-reply' issues

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
  - cron: '28 11 * * *'

jobs:
  close-issues-that-need-reply:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

        stale-issue-label: "needs-reply"
        stale-pr-label: "needs-reply"
        days-before-stale: -1

        days-before-close: 0
        close-issue-message: >
          Closing because the issue author has not replied for 30 days.
          Please let us know when you'd like to work on this further and we'll reopen the issue.

        # close-issue-label: "no reply timeout"



# https://github.com/dessant/lock-threads
# issue-lock-inactive-days
# issue-lock-reason
