name: sit-rep

on:
  workflow_dispatch:
  issue_comment:
    types: [created]
  issues:
    types: [edited]


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: getenv
        run: |
          env
