name: sit-rep

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main


jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: sit-rep
        run: |
          where conda
          where python
          where R
        shell: cmd.exe
          
