name: stat

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main


jobs:
  R-CMD-check:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest, macOS-latest]


    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          # install R on mac because the default image ships w/ homebrew R,
          # which is incompatible w/ CRAN binaries.
          # install-r: ${{ startsWith(matrix.os, 'macOS') }}

      - run: Rscript --version

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # https://r-lib.github.io/pkgdepends/reference/pkg_refs.html#github-packages-
          extra-packages: rstudio/reticulate
          upgrade: 'TRUE'
          cache-version: 2 # bump to invalidate cache

          #local::. rcmdcheck remotes tensorflow

      - run: |
          print(uv <- reticulate:::uv_binary())
          system2(uv, "--version")
          system2(uv, "self update")
        shell: Rscript {0}

      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.8'

      # - run: reticulate::virtualenv_starter(all = TRUE)
      #   shell: Rscript {0}

      # - run: which -a python
      #   shell: bash

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      # - name: setup r-reticulate venv
      #   shell: Rscript {0}
      #   run: |

      #     library(reticulate)

      #     path_to_venv <- virtualenv_create(
      #       envname = "r-reticulate",
      #       python = Sys.which("python"), # placed on PATH by the setup-python action
      #       packages = c(
      #         "docutils", "pandas", "scipy", "matplotlib", "ipython",
      #         "tabulate", "plotly", "psutil", "kaleido", "wrapt"
      #       )
      #     )

      #     writeLines(
      #       paste0("RETICULATE_PYTHON=", virtualenv_python(path_to_venv)),
      #       Sys.getenv("GITHUB_ENV"))


      # - shell: bash
      #   run: env

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      # - run: R -e 'reticulate::virtualenv_starter(all = TRUE)'


# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v4
#         with:
#           python-version: 3.9


      # - name: sit-rep
      #   run: |
      #     where conda
      #     where python
      #     where R
      #   shell: cmd

      # - uses: actions/checkout@v2

      # - uses: r-lib/actions/setup-pandoc@v2

      # - uses: r-lib/actions/setup-r@v2
      #   with:
      #     use-public-rspm: true

      # - uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     extra-packages: rcmdcheck, reticulate
