name: sit-rep

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main


jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: sit-rep
        run: |
          where conda
          where python
          where R
        shell: cmd

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rcmdcheck, reticulate
          
    # - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
