name: sit-rep

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  #     - main


jobs:
  R-CMD-check:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]


    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          # install R on mac because the default image ships w/ homebrew R,
          # which is incompatible w/ CRAN binaries.
          install-r: ${{ startsWith(matrix.os, 'macOS') }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          upgrade: 'TRUE'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: reticulate

          #local::. rcmdcheck remotes tensorflow
          # cache-version: 1 # bump to invalidate cache

      - run: Rscript --version

      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.8'

      - run: reticulate::virtualenv_starter(all = TRUE)
        shell: Rscript {0}

      # - run: which -a python
      #   shell: bash

      # - shell: bash
      #   run: env

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v4
#         with:
#           python-version: 3.9


      # - name: sit-rep
      #   run: |
      #     where conda
      #     where python
      #     where R
      #   shell: cmd

      # - uses: actions/checkout@v2

      # - uses: r-lib/actions/setup-pandoc@v2

      # - uses: r-lib/actions/setup-r@v2
      #   with:
      #     use-public-rspm: true

      # - uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     extra-packages: rcmdcheck, reticulate
