name: sit-rep

on:
  workflow_dispatch:


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
