name: 'test setup-r-tensorflow'

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  R-CMD-check:
    name: ${{ matrix.os }}, tf-${{ matrix.tf }}, R-${{ matrix.r}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: 'ubuntu-20.04'  , tf: 'default-cpu', r: 'release'}
          # - {os: 'windows-latest', tf: 'default-cpu', r: 'oldrel-1'}
          # - {os: 'macOS-latest'  , tf: 'default-cpu', r: 'release'}

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.tf == 'nightly' || contains(matrix.tf, 'rc') || matrix.r == 'devel' }}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: 'true'
      R_COMPILE_AND_INSTALL_PACKAGES: 'never'
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}


    steps:
      - uses: t-kalinowski/gh-actions-playground/setup-r-tensorflow@main
        with:
          install-r: false
          install-miniconda: false
